Added cluster validator webhook with unique local cluster CR validation
cisco-open/cluster-registry-controller pull request #22
Opened 2022-05-13 02:27 UTC by pregnor

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | STB-554
| License         | Apache 2.0

### What's in this PR?

1. Implemented a validating admission webhook for cluster CR validations.
2. Also implemented a validation for ensuring unique local cluster CRs based on cluster type (local) and cluster ID (unique).

**By default the cluster CR validator webhook is turned on through Helm chart values.** Let me know if it should be turned off by default.

### Why?

To disallow creating cluster CRs with cluster ID already belonging to an existing local typed cluster CR.
This is an improvement for multicluster SDM setups.

### Additional context

I based most of the implementation (util conversion functions, k8sutil, certificate provisioner, webhook skeleton) on the banzaicloud/istio-operator#525 PR.
I had to fix some linter issues in the ported code.

I also added somewhat excessive logging - 3 lines per admission request - to the cluster validator webhook implementation, let me know if it is too much so I can trim it down.

Tested manually with the following scenarios:
1. Allowed creating local cluster CR successfully.

```yaml
kind: Cluster
apiVersion: clusterregistry.k8s.cisco.com/v1alpha1
metadata:
  name: pregnor-1
spec:
  authInfo:
    secretRef:
      name: pregnor-1
      namespace: cluster-registry
  clusterID: 80feb07e-3c69-4b98-a576-f62d5df65566
  kubernetesApiEndpoints:
  - serverAddress: https://3.72.141.112:6444
```

2. Allowed updating local cluster CR with identical cluster ID and name compared to existing local cluster CR.

```yaml
kind: Cluster
apiVersion: clusterregistry.k8s.cisco.com/v1alpha1
metadata:
  name: pregnor-1
spec:
  authInfo:
    secretRef:
      name: pregnor-1
      namespace: cluster-registry
  clusterID: 80feb07e-3c69-4b98-a576-f62d5df65566
  kubernetesApiEndpoints:
  - serverAddress: https://3.72.141.112:6443
```

3. Rejected creating local cluster CR with identical cluster ID and different name compared to existing local cluster CR.

```yaml
kind: Cluster
apiVersion: clusterregistry.k8s.cisco.com/v1alpha1
metadata:
  name: pregnor-1-2
spec:
  authInfo:
    secretRef:
      name: pregnor-1-2
      namespace: cluster-registry
  clusterID: 80feb07e-3c69-4b98-a576-f62d5df65566
  kubernetesApiEndpoints:
  - serverAddress: https://3.72.141.112:6443
```

4. Allowed creating peer cluster CR with different cluster ID and name compared to existing local cluster CR.

```yaml
kind: Cluster
apiVersion: clusterregistry.k8s.cisco.com/v1alpha1
metadata:
  name: pregnor-2
spec:
  authInfo:
    secretRef:
      name: pregnor-2
      namespace: cluster-registry
  clusterID: 7aa85423-31c6-4029-98fc-7fff3e440693
  kubernetesApiEndpoints:
  - serverAddress: https://3.70.12.109:6443
```

### Checklist

- [X] Implementation tested
- ~User guide and development docs updated (if needed)~

2022-05-13 02:37 UTC, pregnor commented
CC: @Laci21 , @waynz0r  (as I cannot add reviewers)

2022-05-13 10:11 UTC, pregnor commented
To be cleaned up, there were a couple mistaken cross-references left in from code taken from earlier implementations.

2022-05-13 16:08 UTC, stoader requested changes

2022-05-13 16:08 UTC, stoader commented on go.mod
> +	k8s.io/apiextensions-apiserver v0.21.3
Can we use version `v0.23.1`?

2022-05-13 16:23 UTC, stoader requested changes

2022-05-13 16:23 UTC, stoader commented on pkg/cert/certificate_provisioner.go
> +			Organization: []string{"istio-operator"},
Can't we just set common name instead of organization and set to `cluster-registry-controller-ca`?

2022-05-13 16:33 UTC, stoader requested changes

2022-05-13 16:33 UTC, stoader commented on pkg/cert/certificate_provisioner.go
> +			Organization: []string{"istio-operator"},
I believe organization can be omitted of common name is provided.

2022-05-13 16:33 UTC, stoader commented on pkg/k8sutil/desired_state.go
> +	detachedPodLabel = "istio.banzaicloud.io/detached-pod"
The label domain should be in line with cluster registry (e.g. `clusterregistry.k8s.cisco.com/detached-pod`)

2022-05-13 16:33 UTC, stoader commented on pkg/k8sutil/predicates.go
> +func GetWatchPredicateForIstio() predicate.Funcs {
Cluster registry controller should not watch istio-operator related types.

2022-05-30 10:28 UTC, pregnor commented on go.mod
> +	k8s.io/apiextensions-apiserver v0.21.3
Fixed in https://github.com/cisco-open/cluster-registry-controller/compare/a0fb60a438bc2210e4dae9bc4992473b00263051..a4c0ccb10620a661c53c92315574dca2d72d4a99 .

Removed the code directly depending on it, it remained as an indirect dependency used by the cluster-registry-controller.

2022-05-30 10:29 UTC, pregnor commented on pkg/cert/certificate_provisioner.go
> +			Organization: []string{"istio-operator"},
Fixed in https://github.com/cisco-open/cluster-registry-controller/compare/a0fb60a438bc2210e4dae9bc4992473b00263051..a4c0ccb10620a661c53c92315574dca2d72d4a99 .

Removed the organization.

2022-05-30 10:30 UTC, pregnor commented on pkg/k8sutil/desired_state.go
> +	detachedPodLabel = "istio.banzaicloud.io/detached-pod"
Fixed in https://github.com/cisco-open/cluster-registry-controller/compare/a0fb60a438bc2210e4dae9bc4992473b00263051..a4c0ccb10620a661c53c92315574dca2d72d4a99 .

Removed this code.

2022-06-07 12:40 UTC, Laci21 approved these changes

2022-06-08 10:50 UTC, waynz0r requested changes

2022-06-08 10:50 UTC, waynz0r commented on deploy/charts/cluster-registry/templates/service.yaml
> +      name: cl-val-wh
can we use http-cl-val-wh as a name instead?

2022-06-15 14:08 UTC, pregnor commented on deploy/charts/cluster-registry/templates/service.yaml
> +      name: cl-val-wh
Fixed in https://github.com/cisco-open/cluster-registry-controller/pull/22/commits/aa3f05ffe506a32c991eb4223f0ba44c18e5e2f2

2022-06-15 16:49 UTC, waynz0r approved these changes

2022-06-16 08:01 UTC, merged