Allow mutate target ns
cisco-open/cluster-registry-controller pull request #51
Opened 2023-05-01 00:52 UTC by BEvgeniyS

| Q               | A
| --------------- | ---
| Bug fix?        | maybe
| New feature?    | maybe
| API breaks?     | no
| Deprecations?   | no
| Related tickets | Hopefully fixes https://github.com/cisco-open/cluster-registry-controller/issues/50
| License         | Apache 2.0

### What's in this PR?
This change
- Mutates the namespace prior to checking the target namespace existence
- allows to track original namespace same way we track original name.

### Why?
Currently, if we mutate object's namespace, it gets created and immediately deleted. See more in linked issue

### Checklist
- [x] Implementation tested
- [ ] User guide and development docs updated (if needed)

2023-05-04 04:12 UTC, BEvgeniyS commented
CC: @pregnor @waynz0r @Laci21 @tiswanso

2023-05-04 12:08 UTC, waynz0r commented
Hi @BEvgeniyS,

thanks for the PR!

It looks fine at first glance, but some internal testing seems adequate as namespace mutation could cause tricky side effects.

2023-05-09 23:22 UTC, BEvgeniyS commented
@waynz0r @pregnor Thanks for the review.
When you say internal testing, you mean you'd like to test it yourself or that you'd like to see some unit tests for this change?

2023-05-10 21:32 UTC, waynz0r requested changes

2023-05-10 21:33 UTC, waynz0r commented
> When you say internal testing, you mean you'd like to test it yourself or that you'd like to see some unit tests for this change?

I meant to test it ourselves and I just did.

2023-05-12 20:35 UTC, waynz0r commented on controllers/sync_reconciler.go
>  			Name: req.Namespace,
```suggestion
			Name: obj.GetNamespace(),
```

2023-05-12 20:37 UTC, waynz0r requested changes
requested change is commented

2023-05-15 10:40 UTC, waynz0r approved these changes
thanks @BEvgeniyS!

2023-05-15 10:44 UTC, pregnor approved these changes
LGTM

2023-05-15 10:48 UTC, merged